version: "2.2"

services:
  appcontainer.com:
    build:
      context: .
    ports:
      - 4000:4000
    command: python manage.py runserver 0.0.0.0:4000

  documentserver:
    image: onlyoffice/documentserver
    ports:
      - 80:80

networks:
  default:
    external:
      name: onlyoffice_dev