version: "2.2"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.dev.conf:/etc/nginx/nginx.dev.conf:ro
    command: [ nginx-debug, '-g', 'daemon off;', '-c', '/etc/nginx/nginx.dev.conf']
    depends_on:
      - appcontainer
      - documentserver

  appcontainer:
    build:
      context: .
    ports:
      - 3999:3999
    command: python manage.py runserver 0.0.0.0:3999

  documentserver:
    image: onlyoffice/documentserver
    ports:
      - 1080:80

networks:
  default:
    external:
      name: onlyoffice_dev